Repository Step3-kakao-tech-campus/Team11_BE, pull requests merged in 2023-10, with the labels that each got.

#28 [FEAT] 무한스크롤 시 사용할 response 추가
  src/main/java/com/kakao/golajuma/common/support/respnose/SliceResponse.java
Labels: Type:Feature, Priority:High

#39 [REFACTOR] comment 리팩토링1
  src/main/java/com/kakao/golajuma/comment/domain/exception/NullPointerException.java
  src/main/java/com/kakao/golajuma/comment/domain/service/CommentService.java
  src/main/java/com/kakao/golajuma/comment/domain/utils/CommentCommomLogic.java
  src/main/java/com/kakao/golajuma/comment/domain/utils/CommentValidators.java
  src/main/java/com/kakao/golajuma/comment/domain/utils/SearchUserData.java
  src/main/java/com/kakao/golajuma/comment/infra/entity/CommentEntity.java
  src/main/java/com/kakao/golajuma/comment/infra/repository/CommentRepository.java
  src/main/java/com/kakao/golajuma/comment/web/controller/CommentController.java
  src/main/java/com/kakao/golajuma/comment/web/dto/response/ReadCommentDto.java
  src/main/java/com/kakao/golajuma/comment/web/dto/response/ReadCommentListResponse.java
  src/main/java/com/kakao/golajuma/comment/web/dto/response/SaveCommentResponse.java
  src/main/java/com/kakao/golajuma/comment/web/dto/response/UpdateCommentResponse.java
  src/main/java/com/kakao/golajuma/vote/domain/service/VoteService.java
  src/main/java/com/kakao/golajuma/vote/web/controller/VoteRestController.java
Labels: Priority:Medium

#53 [Feat] decision persistence layer 계층 추가
  src/main/java/com/kakao/golajuma/vote/infra/entity/DecisionEntity.java
  src/main/java/com/kakao/golajuma/vote/infra/repository/DecisionRepository.java
Labels: Type:Feature, Priority:High

#54 [REFACTOR] 투표 리스트 조회 공통 응답 DTO 리팩토링
  src/main/java/com/kakao/golajuma/vote/domain/service/CreateVoteService.java
  src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteDetailService.java
  src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteListService.java
  src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteService.java
  src/main/java/com/kakao/golajuma/vote/infra/entity/OptionEntity.java
  src/main/java/com/kakao/golajuma/vote/infra/entity/VoteEntity.java
  src/main/java/com/kakao/golajuma/vote/infra/repository/OptionRepository.java
  src/main/java/com/kakao/golajuma/vote/infra/repository/VoteRepository.java
  src/main/java/com/kakao/golajuma/vote/util/OptionCheck.java
  src/main/java/com/kakao/golajuma/vote/util/OptionValidator.java
  src/main/java/com/kakao/golajuma/vote/web/dto/request/CreateVoteRequest.java
  src/main/java/com/kakao/golajuma/vote/web/dto/response/CountOptionDto.java
  src/main/java/com/kakao/golajuma/vote/web/dto/response/GetVoteDetailResponse.java
  src/main/java/com/kakao/golajuma/vote/web/dto/response/GetVoteListResponse.java
  src/main/java/com/kakao/golajuma/vote/web/dto/response/OptionDto.java
  src/main/java/com/kakao/golajuma/vote/web/dto/response/VoteDto.java
  src/test/java/com/kakao/golajuma/vote/GetVoteListControllerTest.java
Labels: Priority:Medium

#26 [DOCS] dummydata 생성
  resources/local-develop-environment/docker-compose.yml
  resources/local-develop-environment/mysql-init.d/01_create_table.sql
  resources/local-develop-environment/mysql-init.d/02_insert_data.sql
  src/main/resources/data.sql
Labels: Priority:Low

#103 [FEAT] 투표 참여, 취소 구현
  src/main/java/com/kakao/golajuma/comment/infra/entity/CommentEntity.java
  src/main/java/com/kakao/golajuma/vote/domain/converter/DecisionEntityConverter.java
  src/main/java/com/kakao/golajuma/vote/domain/exception/CompletionVoteException.java
  src/main/java/com/kakao/golajuma/vote/domain/exception/ExistsDecisionException.java
  src/main/java/com/kakao/golajuma/vote/domain/exception/NotFoundDecisionException.java
  src/main/java/com/kakao/golajuma/vote/domain/service/DecisionService.java
  src/main/java/com/kakao/golajuma/vote/infra/entity/OptionEntity.java
  src/main/java/com/kakao/golajuma/vote/infra/entity/VoteEntity.java
  src/main/java/com/kakao/golajuma/vote/infra/repository/DecisionRepository.java
  src/main/java/com/kakao/golajuma/vote/infra/repository/OptionRepository.java
  src/main/java/com/kakao/golajuma/vote/web/controller/DecisionController.java
  src/main/java/com/kakao/golajuma/vote/web/dto/converter/DecisionResponseConverter.java
  src/main/java/com/kakao/golajuma/vote/web/dto/converter/OptionResultConverter.java
  src/main/java/com/kakao/golajuma/vote/web/dto/response/DecisionResponse.java
  src/main/java/com/kakao/golajuma/vote/web/dto/response/OptionResult.java
Labels: Type:Feature, Priority:High

#107 [Fix] 투표 조회 시 옵션 중복 문제 해결
  src/main/java/com/kakao/golajuma/vote/web/dto/response/VoteDto.java
Labels: Type:Bug

#109 [FIX] option에 맞는 vote 가져오는 쿼리 메서드 추가
  src/main/java/com/kakao/golajuma/vote/domain/service/DecisionService.java
  src/main/java/com/kakao/golajuma/vote/infra/entity/OptionEntity.java
  src/main/java/com/kakao/golajuma/vote/infra/entity/VoteEntity.java
  src/main/java/com/kakao/golajuma/vote/infra/repository/VoteRepository.java
Labels: Type:Bug, Priority:High

#113 [Feat] 투표 마감 기능
  src/main/java/com/kakao/golajuma/vote/domain/exception/CloseException.java
  src/main/java/com/kakao/golajuma/vote/domain/service/CloseVoteService.java
  src/main/java/com/kakao/golajuma/vote/domain/service/CreateVoteService.java
  src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteListService.java
  src/main/java/com/kakao/golajuma/vote/infra/entity/VoteEntity.java
  src/main/java/com/kakao/golajuma/vote/web/controller/CloseVoteController.java
  src/main/java/com/kakao/golajuma/vote/web/controller/GetVoteDetailController.java
Labels: Type:Feature, Priority:Medium

#117 [Refactor] 투표 리스트 조회 방식 리팩토링
  src/main/java/com/kakao/golajuma/vote/domain/exception/SortException.java
  src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteListService.java
  src/main/java/com/kakao/golajuma/vote/domain/service/Sort.java
  src/main/java/com/kakao/golajuma/vote/infra/entity/Active.java
  src/main/java/com/kakao/golajuma/vote/infra/entity/Category.java
  src/test/java/com/kakao/golajuma/vote/GetVoteListControllerTest.java
Labels: Priority:High, Type:Refactor

#122 [Refactor] 투표 검색 기능 리팩토링
  src/main/java/com/kakao/golajuma/vote/domain/service/SearchVoteListService.java
  src/main/java/com/kakao/golajuma/vote/infra/repository/VoteRepository.java
  src/main/java/com/kakao/golajuma/vote/web/controller/CloseVoteController.java
  src/test/java/com/kakao/golajuma/vote/SearchVoteListControllerTest.java
Labels: Priority:High, Type:Refactor

#131 [Refactor] 참여한 투표 리스트 조회 쿼리 추가
  src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteListService.java
  src/main/java/com/kakao/golajuma/vote/domain/service/GetVoteService.java
  src/main/java/com/kakao/golajuma/vote/infra/repository/VoteRepository.java
  src/test/java/com/kakao/golajuma/vote/GetVoteListControllerTest.java
Labels: Type:Feature, Priority:High, Type:Refactor

#136 [Refactor] 이미지 처리 수정
  src/main/java/com/kakao/golajuma/vote/infra/entity/OptionEntity.java
  src/main/java/com/kakao/golajuma/vote/util/ImageUploader.java
Labels: Priority:High, Type:Refactor

#139 [FIX] 투표 취소 시 에러 null 오류 해결
  src/main/java/com/kakao/golajuma/vote/web/dto/converter/DecisionResponseConverter.java
Labels: Type:Bug

#140 [Refactor] 이미지 업로드 경로 변경 및 인코딩 코드 추가
  src/main/java/com/kakao/golajuma/vote/util/ImageUploader.java
  src/main/java/com/kakao/golajuma/vote/web/dto/response/CountOptionDto.java
  src/main/java/com/kakao/golajuma/vote/web/dto/response/OptionDto.java
Labels: Priority:High, Type:Refactor
