Repository Step3-kakao-tech-campus/Team11_BE, pull requests merged in 2023-11, with the labels that each got.

#157 [Test] 투표 마감 서비스 테스트 코드 추가
  src/main/java/com/kakao/golajuma/vote/web/dto/request/CreateVoteRequest.java
  src/test/java/com/kakao/golajuma/vote/api/CreateVoteControllerTest.java
  src/test/java/com/kakao/golajuma/vote/api/GetVoteDetailControllerTest.java
  src/test/java/com/kakao/golajuma/vote/api/SearchVoteListControllerTest.java
  src/test/java/com/kakao/golajuma/vote/domain/service/CloseVoteServiceTest.java
Labels: Priority:Medium, Type:Test

#163 [FEAT] decision 업데이트 구현
  src/main/java/com/kakao/golajuma/vote/domain/exception/NotFoundVoteException.java
  src/main/java/com/kakao/golajuma/vote/domain/service/DecisionService.java
  src/main/java/com/kakao/golajuma/vote/web/controller/DecisionController.java
  src/main/java/com/kakao/golajuma/vote/web/dto/converter/DecisionResponseConverter.java
  src/main/java/com/kakao/golajuma/vote/web/dto/converter/OptionResultConverter.java
  src/main/java/com/kakao/golajuma/vote/web/dto/response/DecisionResponse.java
  src/main/java/com/kakao/golajuma/vote/web/dto/response/OptionResult.java
Labels: Type:Feature, Priority:High

#165 [FIX] 토큰 관련 변경
  src/main/java/com/kakao/golajuma/auth/domain/service/CreateTokenService.java
  src/main/java/com/kakao/golajuma/auth/web/controller/LoginController.java
  src/main/java/com/kakao/golajuma/auth/web/dto/converter/TokenConverter.java
  src/main/java/com/kakao/golajuma/auth/web/dto/response/TokenResponse.java
  src/main/resources/application-dev-token.yml
  src/test/java/com/kakao/golajuma/auth/domain/service/ValidEmailServiceTest.java
  src/test/java/com/kakao/golajuma/auth/domain/service/ValidNicknameServiceTest.java
Labels: Priority:High

#168 [FEAT] 엑세스 토큰 재발급 기능
  src/main/java/com/kakao/golajuma/auth/domain/service/ReissueService.java
  src/main/java/com/kakao/golajuma/auth/web/controller/AuthController.java
  src/main/java/com/kakao/golajuma/auth/web/support/CookieExtractor.java
Labels: Type:Feature, Priority:High

#173 [FEAT] 비로그인자 접근 가능 기능 추가
  src/main/java/com/kakao/golajuma/auth/web/interceptor/AuthInterceptor.java
  src/main/java/com/kakao/golajuma/auth/web/support/AnonymousAvailable.java
  src/main/java/com/kakao/golajuma/auth/web/support/AuthenticationPrincipalArgumentResolver.java
  src/main/java/com/kakao/golajuma/config/WebMvcConfig.java
Labels: Type:Feature, Priority:High

#176 [Refactor] 비로그인 사용자 어노테이션 적용
  src/main/java/com/kakao/golajuma/vote/web/controller/GetVoteDetailController.java
  src/main/java/com/kakao/golajuma/vote/web/controller/GetVoteListController.java
  src/main/java/com/kakao/golajuma/vote/web/controller/SearchVoteListController.java
Labels: Priority:High, Type:Refactor

#190 [Test] 투표 테스트 추가 (투표 리스트 조회 단위 테스트 추가, 투표 마감, 리스트 조회 통합 테스트 추가)
  src/test/java/com/kakao/golajuma/vote/api/CloseVoteControllerTest.java
  src/test/java/com/kakao/golajuma/vote/api/GetVoteListControllerTest.java
  src/test/java/com/kakao/golajuma/vote/domain/service/GetVoteListServiceTest.java
  src/test/java/com/kakao/golajuma/vote/domain/service/SearchVoteListServiceTest.java
Labels: Priority:High, Type:Test

#203 [REFACTOR] exception 리팩터링
  src/main/java/com/kakao/golajuma/auth/domain/exception/AuthenticationTokenNotFoundException.java
  src/main/java/com/kakao/golajuma/auth/domain/exception/AuthorizationException.java
  src/main/java/com/kakao/golajuma/auth/domain/exception/InvalidTokenFormatException.java
  src/main/java/com/kakao/golajuma/auth/domain/exception/NotFoundTokenException.java
  src/main/java/com/kakao/golajuma/auth/domain/exception/NotValidToken.java
  src/main/java/com/kakao/golajuma/auth/domain/exception/TokenExpiredException.java
  src/main/java/com/kakao/golajuma/auth/web/support/AuthenticationPrincipalArgumentResolver.java
  src/main/java/com/kakao/golajuma/vote/domain/exception/CompletionVoteException.java
  src/main/java/com/kakao/golajuma/vote/domain/exception/ExistsDecisionException.java
  src/main/java/com/kakao/golajuma/vote/domain/exception/NotFoundDecisionException.java
  src/main/java/com/kakao/golajuma/vote/domain/exception/NotFoundDecisionOptionException.java
  src/main/java/com/kakao/golajuma/vote/domain/exception/NotFoundDecisionVoteException.java
  src/main/java/com/kakao/golajuma/vote/domain/exception/NotFoundOptionException.java
  src/main/java/com/kakao/golajuma/vote/domain/exception/NotFoundVoteException.java
  src/main/java/com/kakao/golajuma/vote/domain/service/DecisionService.java
Labels: Type:Bug, Priority:High

#229 [Refactor] 투표 생성 시 예외처리 추가
  src/main/java/com/kakao/golajuma/vote/infra/entity/OptionEntity.java
  src/main/java/com/kakao/golajuma/vote/web/dto/request/CreateVoteRequest.java
Labels: Priority:High, Type:Refactor

#236 [REFACTOR] 투표 검색 full text search 변경 및 투표 글자 수 제한 추가
  src/main/java/com/kakao/golajuma/vote/persistence/entity/OptionEntity.java
  src/main/java/com/kakao/golajuma/vote/persistence/entity/VoteEntity.java
  src/main/java/com/kakao/golajuma/vote/persistence/repository/VoteRepository.java
  src/main/java/com/kakao/golajuma/vote/web/dto/request/CreateVoteRequest.java
  src/test/java/com/kakao/golajuma/vote/web/controller/SearchVotesControllerTest.java
Labels: Priority:High, Type:Refactor

#227 [FEAT] CI 설정
  .github/workflows/backend-ci.yml
Labels: Type:Feature, Priority:High
